name: lqb2's communication protocols
description: how i communicate
meta_description: "this is where i explain how to communicate with me best"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /protocols/
domain_name: 'http://lqb2.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://lqb2.github.io'
author:         'Lawrence Barriner II'
